eight_points_guzzle:
    clients:
        api_recipes_puppy:
            base_url: "http://www.recipepuppy.com/api"
            options:
                headers:
                    Accept: "application/json"
