eight_points_guzzle:
    clients:
        api_recipes_puppy:
            base_url: "http://www.recipepuppy.com/api/"
            options:
                headers:
                    Accept: "application/json"
                curl:
                    sslversion: 1 # or !php/const:CURL_HTTP_VERSION_1_0 for symfony >= 3.2
                    timeout: 30
