eight_points_guzzle:
  # (de)activate logging/profiler; default: %kernel.debug%
  logging: true

  clients:
    api_recipes_puppy:
      base_url: "http://www.recipepuppy.com/api/"
        headers:
          Accept: "application/json"

        # Find proper php const, for example CURLOPT_SSLVERSION, remove CURLOPT_ and transform to lower case.
        # List of curl options: http://php.net/manual/en/function.curl-setopt.php
        curl:
          sslversion: 1 # or !php/const:CURL_HTTP_VERSION_1_0 for symfony >= 3.2

        timeout: 30

      # plugin settings
      plugin: ~